### PR TITLE
Makes changes suggested in #4, fixes #4

### LINKED ISSUE #4: Change variables to be lowercase to not confuse with bash enviroment variables
E.g. `CHOICE` and `TASK`

### PR DESCRIPTION
**Pull request by fippli**
- Renames camelCase stuff to lower_underscore
- Renames variables with UPPERCASE to lowercase

### CODE REVIEW

**Review by bombsimon — APPROVED** [review]
Oops, I started with this as well! But let's merge this and resolve potential conflicts!

**Comment by fippli** [comment]
Haha! Both are too excited about the amazing updates!

**Comment by fippli** [comment]
I also started on the installation thing. Did you as well?

**Comment by bombsimon** [comment]
Yup, I did! Have a PR incoming so ABORT!!!! ⚠️

**Comment by fippli** [comment]
Ok, I'll skip it then :)

**Pull request merged**
