### PR TITLE
Description

### PR DESCRIPTION
**Pull request by fippli**
- Adds support for meta rows `[:this-is-some-meta-data]`
- Meta rows are ignored when printing
- Adds support for description in the meta row `[:description]`
- Adds command `--describe` to edit the description of the todo-file

### CODE REVIEW

**Comment by fippli** [comment]
Maybe the command should be `--meta description` to be more flexible for any type of meta field in the list?

**Review by bombsimon — CHANGES_REQUESTED** [review]
> Maybe the command should be `--meta description` to be more flexible for any type of meta field in the list?

I think we can wait with that until we see more uses of meta data.

The help output should be updated to show the flag, didn't see it first because I didn't read your comment in the PR. :)

**EDIT**: Also, should this work on old lists? If I checkout this branch en run `todo --describe` I get the description prompt but it doesn't have any effect.

**EDIT2**: Ohh, it always uses the `~/.todo` file even if I have ha local one at `./.todo`. It works if I run `todo --task-file .todo --describe` but that should probably be automatic.

**Comment by bombsimon** [comment]
It seems to be more bugs with the `--describe` flag as well, there's a problem when there's a description already.

```sh
$ cat .todo
[<]You
[>]Test Again :)
[<]This is task

$ todo --task-file .todo --describe
        EDIT DESCRIPTION: XX

$ cat .todo
[<]You
[>]Test Again :)
[<]This is task
[:description]XX

$ todo --task-file .todo --describe
        EDIT DESCRIPTION: YY

$ cat .todo
[<]You
[>]Test Again :)
[<]This is task
[:description]XX
[:description]YY

# XX was pre filled
$ todo --task-file .todo --describe
        EDIT DESCRIPTION: XX YY

$ cat .todo
[<]You
[>]Test Again :)
[<]This is task

[:description]YY
```
```

**Comment by fippli** [comment]
Thanks for the review! I'll look into it :)

**Pull request closed without merging**
